<?php
/*
 * The MIT License
 *
 * Copyright 2018 Jim Baize <pavulon@hotmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>

<img id="top" src="/assets/graphics/top.png" alt="">
<div id="form_container">

    <h1><a>Change Password Form</a></h1>
    <form id="resetPassword" class="appnitro"  method="post" action="<?php htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        <div class="form_description">
            <h2>Change Password Form</h2>
            <p>Please enter the required information in the following fields.</p>
        </div>						
        <ul >
            <li id="oldPassword" >
                <label class="description" for="oldPassword">Old Password </label>
                <div>
                    <input id="oldPassword" name="oldPassword" class="element text medium" type="password" maxlength="255" value=""/> 
                </div> 
            </li>
            <li class="section_break">
                <h3></h3>
                <p></p>
            </li>
            <li id="newPassword1" >
                <label class="description" for="newPassword1">New Password </label>
                <div>
                    <input id="newPassword1" name="newPassword1" class="element text medium" type="password" maxlength="255" value=""/> 
                </div> 
            </li>
            <li id="newPassword2" >
                <label class="description" for="newPassword2">Confirm New Password </label>
                <div>
                    <input id="newPassword2" name="newPassword2" class="element text medium" type="password" maxlength="255" value=""/> 
                </div> 
            </li>

            <li class="buttons">
                <input type="hidden" name="form_id" value="706" />

                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
            </li>
        </ul>
    </form>	
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="/assets/graphics/bottom.png" alt="">