<?php
/*
 * The MIT License
 *
 * Copyright 2018 Jim Baize <pavulon@hotmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>

<img id="top" src="/assets/graphics/top.png" alt="">
<div id="form_container">

    <h1><a>Change Password Form</a></h1>
    <form id="form_6239" class="appnitro" method="post" action="<?php htmlspecialchars($_SERVER["PHP_SELF"]); ?>">
        <div class="form_description">
            <h2>Change Password Form</h2>
            <p>Please enter the name of the employee and a new password for the employee.  The old password will be revoked.</p>
        </div>						
        <ul >
            <li id="employee_number" >
                <label class="description" for="empNum">Employee Number </label>
                <div>
                    <input id="empNum" name="empNum" class="element text medium" type="text" maxlength="9" value=""/> 
                </div> 
            </li>
            <li id="passwordOne" >
                <label class="description" for="password">Password </label>
                <div>
                    <input id="password" name="password" class="element text medium" type="password" maxlength="255" value="" required=""/> 
                </div> 
            </li>
            <li id="passwordTwo" >
                <label class="description" for="password">Retype Password </label>
                <div>
                    <input id="password" name="password2" class="element text medium" type="password" maxlength="255" value="" required=""/> 
                </div> 
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="6239" />
                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
            </li>
        </ul>
    </form>	
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="/assets/graphics/bottom.png" alt="">